from prompt_toolkit.output.win32 import BACKGROUND_COLOR

from config.PageConstant import SCREEN_HEIGHT, SCREEN_WIDTH_CENTER

# GAMEPLAY BOX
BASE_SPEED = 4
MULTI_SPEED = 1

MOVE_UP = (0, 1)
MOVE_LEFT = (-1, 0)
MOVE_RIGHT = (1, 0)
MOVE_DOWN = (0, -1)

__ADJUSTMENT_EDGE_LINE = 1.2 ## IMPORTANT TO REFINE
ADJUSTMENT_MULTI = __ADJUSTMENT_EDGE_LINE

BOX_CHECKER_COLOR = (63, 169, 245)
BOX_CHECKER_GAP = 20 * (__ADJUSTMENT_EDGE_LINE / 2)
BOX_CHECKER_Y = 678
BOX_CHECKER_HEIGHT = 15
BOX_CHECKER_INNER_SIZE = (220 * __ADJUSTMENT_EDGE_LINE, BOX_CHECKER_HEIGHT)
BOX_CHECKER_OUTER_SIZE = (200 * __ADJUSTMENT_EDGE_LINE, BOX_CHECKER_HEIGHT)
BOX_CHECKER1_COORD = (SCREEN_WIDTH_CENTER - BOX_CHECKER_OUTER_SIZE[0] - BOX_CHECKER_GAP - BOX_CHECKER_OUTER_SIZE[0]/2, BOX_CHECKER_Y)
BOX_CHECKER2_COORD = (SCREEN_WIDTH_CENTER - BOX_CHECKER_INNER_SIZE[0]/2, BOX_CHECKER_Y)
BOX_CHECKER3_COORD = (SCREEN_WIDTH_CENTER + BOX_CHECKER_INNER_SIZE[0]/2, BOX_CHECKER_Y)
BOX_CHECKER4_COORD = (SCREEN_WIDTH_CENTER + BOX_CHECKER_OUTER_SIZE[0] + BOX_CHECKER_GAP + BOX_CHECKER_OUTER_SIZE[0]/2, BOX_CHECKER_Y)
BOX_CHECKER_CHECKPOINT_COORD = [(BOX_CHECKER_Y - BOX_CHECKER_HEIGHT / 2), (BOX_CHECKER_Y - BOX_CHECKER_HEIGHT), (BOX_CHECKER_Y + BOX_CHECKER_HEIGHT / 2)]

BOX_TEMPO_COLOR = (59, 51, 69)
BOX_TEMPO_THICKNESS = 15 * __ADJUSTMENT_EDGE_LINE
BOX_TEMPO_SIZE = (487.4 * __ADJUSTMENT_EDGE_LINE, BOX_TEMPO_THICKNESS)
BOX_TEMPO_COORD = (SCREEN_WIDTH_CENTER, -BOX_TEMPO_THICKNESS) ##**##

BOX_NOTE_COLORS = [(255, 17, 120), (168, 0, 170), (255, 242, 5), (124, 255, 1)]

# GAME
GAME_SCORE_HEADING_BOX_SIZE = (213, 59)
GAME_SCORE_HEADING_BOX_COLOR = (255, 254, 224)
GAME_SCORE_HEADING_BOX_COORD = (1056.5, 44)

GAME_EDGE_COLOR = (27, 48, 91)
GAME_EDGE_LINE_WIDTH = 440 * __ADJUSTMENT_EDGE_LINE
GAME_EDGE1_COORD_START = (SCREEN_WIDTH_CENTER - GAME_EDGE_LINE_WIDTH, SCREEN_HEIGHT)
GAME_EDGE1_COORD_END = (SCREEN_WIDTH_CENTER, -842 * __ADJUSTMENT_EDGE_LINE)
GAME_EDGE2_COORD_START = (SCREEN_WIDTH_CENTER + GAME_EDGE_LINE_WIDTH, SCREEN_HEIGHT)
GAME_EDGE2_COORD_END = (SCREEN_WIDTH_CENTER, -842 * __ADJUSTMENT_EDGE_LINE)

GAME_EDGE_INNER_LINE_COLOR = (13, 0, 30)
GAME_EDGE_INNER_LINE_RANGE = 230 * __ADJUSTMENT_EDGE_LINE
GAME_EDGE_INNER1_COORD_START = (SCREEN_WIDTH_CENTER - GAME_EDGE_INNER_LINE_RANGE, SCREEN_HEIGHT)
GAME_EDGE_INNER1_COORD_END = (SCREEN_WIDTH_CENTER, -842 * __ADJUSTMENT_EDGE_LINE)
GAME_EDGE_INNER2_COORD_START = (SCREEN_WIDTH_CENTER + GAME_EDGE_INNER_LINE_RANGE, SCREEN_HEIGHT)
GAME_EDGE_INNER2_COORD_END = (SCREEN_WIDTH_CENTER, -842 * __ADJUSTMENT_EDGE_LINE)

GAME_EDGE_CENTER_LINE_COLOR = GAME_EDGE_INNER_LINE_COLOR
GAME_EDGE_CENTER_LINE_START = (SCREEN_WIDTH_CENTER, 0)
GAME_EDGE_CENTER_LINE_END = (SCREEN_WIDTH_CENTER, SCREEN_HEIGHT)
