import pygame

SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 800
SCREEN_WIDTH_CENTER = SCREEN_WIDTH / 2
SCREEN_HEIGHT_CENTER = SCREEN_HEIGHT / 2
SCREEN_DIMENSION = (SCREEN_WIDTH, SCREEN_HEIGHT)
SCREEN_CENTER = (SCREEN_WIDTH_CENTER, SCREEN_HEIGHT_CENTER)
SCREEN_BACKGROUND = (13, 0, 30)

# SCREEN CONFIG

# HOME
HOME_TITLE = "Home"
HOME_STATIC_COMPONENT = []
HOME_DYNAMICS_COMPONENT = None

# SONG
SONG_TITLE = "Select Song"
SONG_STATIC_COMPONENT = []
SONG_DYNAMICS_COMPONENT = []

# GAME
GAME_TITLE = " - Main Game"

GAME_ALIGN_LINE_COLOR = (27, 48, 91)
GAME_ALIGN_LINE_MARGIN = 171

GAME_STATIC_COMPONENT = []
GAME_DYNAMICS_COMPONENT = []

# CREDITS
CREDITS_TITLE = "Credits"
CREDITS_STATIC_COMPONENT = []
CREDITS_DYNAMICS_COMPONENT = None

# LEADERBOARD
LEADERBOARD_TITLE = "Leaderboard"
LEADERBOARD_STATIC_COMPONENT = []
LEADERBOARD_DYNAMICS_COMPONENT = []

